name: PortCall
favicon: null
layout_spectrum: 0.16013
typography_spectrum: 0.32213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cecece'
    - '#34373b'
    - '#1ba396'
    - '#5a5d60'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
