name: PortCall
favicon: null
layout_spectrum: 0.53814
typography_spectrum: 0.32213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.10943611455149949
  lightness: 0.7880504140630364
  saturation: 0.8883790010586381
  rhythmicContrast: 0.34441042225807905
purpose: []
