name: PortCall
favicon: null
layout_spectrum: 0.53814
typography_spectrum: 0.32213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020305'
    - '#cdcdcf'
    - '#3f819c'
    - '#65bef5'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
